trigger:
  branches:
    include:
      - main
      - development

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest coverage pylint
  displayName: 'Install dependencies'

- script: |
    coverage run -m pytest
    coverage report --fail-under=80
    coverage xml
  displayName: 'Run tests with coverage'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage.xml'
    reportDirectory: 'coverage_html_report'
    failIfCoverageEmpty: true

- script: |
    pylint app/*.py
  displayName: 'Run static analysis'
